print('请输入姓名')
name = input()
print('1.水瓶座：1.20-2.18')
print('2.双鱼座：2.19-3.20')
print('3.白羊座：3.21-4.19')
print('4.金牛座:4.20-5.20')
print('5.双鱼座：5.21-6.21')
print('6.巨蟹座：6.21-7.22')
print('7.狮子座：7.23-8.22')
print('8.处女座：8.23-9.22')
print('请根据如上提示选择对应编号')
xingzuo = int(input())
print('请输入日期：××.××')
date = float(input())
if xingzuo == 1:
    print(name)
    print('您好!')
    print('水瓶星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗') 
elif xingzuo == 2: 
    print(name)
    print('您好!')
    print('双鱼星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 3:
    print(name)
    print('您好!')
    print('白羊星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 4:
    print(name)
    print('您好!')
    print('金牛星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 5:
    print(name)
    print('您好!')
    print('双子星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 6:
    print(name)
    print('您好!')
    print('巨蟹星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 7:
    print(name)
    print('您好!')
    print('狮子星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
elif xingzuo == 8:
    print(name)
    print('您好!')
    print('处女星座的您分析结果:')
    print('日期是:%.2f'%date)
    print('性格：开朗')
else:
    print('对不起系统升级，请输入1-8')
